### ISSUE TITLE
Shared Preferences

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#1]
**Description**
Initialize Shared Preferences in the app

**File Location**
```
- data
|__ sharedpreferences
      |___ vost_shared_preferences.dart
- domain
|__ managers
     |___ shared_preferences_manager.dart
```

**Requirements**
- Create class that manages the https://pub.dev/packages/shared_preferences plugin - `VostSharedPreferences`. This class should read and write into the shared Preferences.

- All the keys should `const` and `String`and should be declared as private at the bottom of the file

- Create class that abstracts managing the shared preferences : `SharedPreferencesManager` -> this class will know the default value for each preference, example: if we are trying to get a list of ids, instead of null, we should return an empty array. This class has a `get` and `set` method for each value. If needed, it can also have a `set` method that sets multiple values. 

**NOTE**:
Since that at the start we don't have any values to store, please create a new `String` value to store with the key `test_shared`.

**Comment by joaomagfreitas** [comment]
Hey guys, is this issue assigned to someone? If not I can help :)

**Comment by Vanethos** [comment]
Go ahead @freitzzz !

I'll assign the issue to you

I'm just going to edit the description to be more clear, other than that you're good to go!

**Comment by joaomagfreitas** [comment]
Got it!
Will start working on the issue asap

**Comment by Vanethos** [comment]
@freitzzz any news? Did you manage to have time to complete the PR?

**Comment by Vanethos** [comment]
Due to inactivity, I'm going to remove the assignee of this issue

**Comment by joaomagfreitas** [comment]
> Due to inactivity, I'm going to remove the assignee of this issue

Hi @Vanethos !

Unfortunately I've been very inactive on Github due to work and school consuming most of my work and spare time :( I'm sorry that I wasn't able to help and answer you in time!

I will also make sure that I can work on a PR next time I ask for an assignee on an issue.

Cheers,
freitzzz

**Comment by Vanethos** [comment]
@freitzzz There's no problem in that!

The joy of open-source is being able to contribute to projects when we have time!

And sometimes life just happens or we don't have the time or energy to do it and that's **totally okay** :D 

When we have less time, others will have more time, and vice-versa, so I just removed you from this issue not for "punishment", but because others (in this case myself) had time to finish this off now.

There are plenty of issues still open, and more to come, so please, don't see this as a way to scold you! We want more contributions and yours would be valuable to this project :D

**Comment by TarekkMA** [comment]
Hello, @Vanethos  I'm glad to help with this issue <3. BTW I love the way you structured the app.

**Comment by TarekkMA** [comment]
@Vanethos  can you explain what is the roles for ```VostSharedPreferences``` and ```SharedPreferencesManager```.

Should  ```VostSharedPreferences``` be just a wrapper to ```SharedPreferences``` plugin and  ```SharedPreferencesManager``` methods like ```setUser()``` ?

**Comment by Vanethos** [comment]
@TarekkMA

As you can see this issue has been assigned to me and I have already created a PR for it

But you have other issues that you can do!

**Comment by TarekkMA** [comment]
Oh okay thank you I will select another issue
