### ISSUE TITLE
Native Splash Screen

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#13]
**Description**
Create Native Android and iOS screen for the app

**Requirements**
- See https://medium.com/@diegoveloper/flutter-splash-screen-9f4e05542548 for more details

**UI**

<img width="364" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63039860-1fe8f280-bebc-11e9-911f-6a48d9bf219d.png">

**Comment by Vanethos** [comment]
@OldMetalmind is there a PNG of this image? we will need different sizes for all the IOS screens

**Comment by OldMetalmind** [comment]
The image is at the Zeplin project. 
For anyone wishing to contribute with this issue, please read the contribution guide and join the chat for us to give us access to the Zeplin project and all resources.

**Comment by OldMetalmind** [comment]
I'm doing this Pull Request, I will use the animation made by @ffrutuoso 
Related:
- https://github.com/vostpt/mobile-app/issues/14
