### ISSUE TITLE
Flare Splash Screen

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#14]
**Description**
Create Flutter Splash Screen

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- "This screen will show an animation with the app logo 
- Internally, this screen will check in the shared preferences if the user has opened the app previously
    - If first install, go to tutorial
   - Else, go to main app screen"

**UI**

<img width="364" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63039860-1fe8f280-bebc-11e9-911f-6a48d9bf219d.png">

**Comment by Vanethos** [comment]
@OldMetalmind need animation

**Comment by OldMetalmind** [comment]
@ffrutuoso will be working on animating the logo with [2Dimensions Flare(https://www.2dimensions.com/about-flare)

Let's not work on this before Francisco is able to create the animation.

**Comment by ffrutuoso** [comment]
Animated the logo for the splash screen. First version, here:
[https://www.2dimensions.com/a/ffrutuoso/files/flare/vost-anim-v01/preview](https://www.2dimensions.com/a/ffrutuoso/files/flare/vost-anim-v01/preview)
