### ISSUE TITLE
Onboarding Screen

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#15]
**Description**
Create tutorial for the app

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- When swipping on the screen we go to the next (swipe right) or left (swipe left) screen
- There is one screen with an explanation about the location permission for the app. That screen will have an ""Accept"" and ""Refuse"" buttons
    - Accept will show the OS's permission dialog to accept the permission
    -  Refuse will show a pop-up screen warning the user that some features of the app will not work properly, such as the map

**UI**

![unknown](https://user-images.githubusercontent.com/10728633/67143235-6242fd00-f27a-11e9-97c5-d5b2bec3328e.png)

**Comment by Vanethos** [comment]
@OldMetalmind copy and images needed

**Comment by OldMetalmind** [comment]
Our suggestion is to have 4 screens with the following

1. Who is VOST;
2. What is this App;
3. Sources of the information for the app;
4. *What kind of permissions we ask and why

* This is where we will explain what permissions we need from the device and ask the user if they mind accepting them.

**Comment by Vanethos** [comment]
Issue has been updated with the new UI for this page
