### ISSUE TITLE
Report Problem Screen

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#16]
**Description**
Create Problems Screen

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- Screen with text information about how to report a problem

- Appbar must have a ""back"" button

**UI**
<img width="365" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63040257-ff6d6800-bebc-11e9-9e8a-25b6639cbf8d.png">

**NOTES**
Assume the following text:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In iaculis nunc sed augue. A scelerisque purus semper eget duis at tellus at urna. Quisque sagittis purus sit amet volutpat. Maecenas volutpat blandit aliquam etiam. Eu facilisis sed odio morbi quis commodo odio. Aliquet risus feugiat in ante metus. Nec ullamcorper sit amet risus. Libero id faucibus nisl tincidunt eget nullam. Non consectetur a erat nam at. Cursus eget nunc scelerisque viverra mauris in aliquam sem. At tempor commodo ullamcorper a lacus vestibulum sed. Urna molestie at elementum eu facilisis sed. Fermentum dui faucibus in ornare. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Nunc faucibus a pellentesque sit amet porttitor eget. Nunc sed velit dignissim sodales ut eu sem. Interdum posuere lorem ipsum dolor. Eu mi bibendum neque egestas congue quisque. Convallis convallis tellus id interdum velit laoreet id donec.

email@email.com
```

The email should be clickable and it should open a new e-mail for `email@email.com`.

**Comment by Vanethos** [comment]
@OldMetalmind copy needed

**Comment by 404shades** [comment]
Please assign this issue to me. I can work on this

**Comment by OldMetalmind** [comment]
Ok @404shades we will, please feel free to join our chat is in our Contributions documents.

**Comment by 404shades** [comment]
can you please review. I have opened the pull request

**Comment by Vanethos** [comment]
@404shades we always try our best to be as quick as possible.

Use the issues only to ask questions about the issue or suggest changes to it.
