### ISSUE TITLE
About Screen

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#18]
**Description**
About screen for VOST, including contacts, links to the contributors and tutorial screen

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- Include button to access *Contributors* screen
- Include button to access *Tutorial* screen
- All contacts should be clickable, either launch phone/email apps or use https://pub.dev/packages/url_launcher to open URLs

**UI**
<img width="361" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63055869-b7f7d380-bede-11e9-8a71-3fd19c6bdfe6.png">

**NOTES**

Assume the following test:

```
A VOST Portugal - Associação de Voluntários Em Situações de Emergência - é uma equipa de voluntários digitais que recolhe, valida, e informa as populações em casos de emergência. Esta aplicação, feita integralmente por voluntários e em código aberto, tem como objectivo colocar numa só aplicação mensagens oficiais no âmbito da autoprotecção, desastres naturais, e fenómenos meteorológicos adversos.
```

Assume that in the grid you will receive a `List<Contacts>` in which a Contact can have the following structure:

```
String name;
String imageUrl;
String info;
ContactType type; // this is an enum with the values ["PHONE", "URL", "EMAIL"]
```

Depending on the `type`, a click on this button can either open the phone app with the number ,open an url or send an email.

The buttons at the bottom of the screen should be clickable, so a function should be exposed to place there the callback

**Comment by Vanethos** [comment]
@OldMetalmind Copy will be needed for this issue

**Comment by JorgeMiguelGomes** [comment]
@Vanethos copy will be given ;) You can assign that task to me.

**Comment by Vanethos** [comment]
@JorgeMiguelGomes done!

**Comment by OldMetalmind** [comment]
Let keep this issue open for developers to be assigned and create another issue only for the copy.

**Comment by Thesmader** [comment]
Is it compulsory to use the BLoC architecture for this screen?

**Comment by Vanethos** [comment]
@Thesmader For this screen it is not since it's going to be composed of static data (for now).

If in the future we need to have dynamic data for the contacts, we will update it in a new issue

**Comment by Thesmader** [comment]
I'm interested in taking this issue. Any specific guidelines to follow?

**Comment by Vanethos** [comment]
Sure!

Please read our Contributing guidelines: https://github.com/vostpt/mobile-app/blob/develop/CONTRIBUTING.md

- When a Widget is for a Screen, add the suffix `Page`, `AboutPage` for example
- The file name should be undercased and spaces should be underscores `about_page.dart`
- When possible use `StatelessWidgets`
- Add a route to the `app.dart` file (iirc) in order to navigate to that screen
- Have fun!

**Comment by Vanethos** [comment]
@Thesmader The text for this screen will be added in a few minutes.

I'll assign this issue to you

**Comment by Thesmader** [comment]
Thank you, @Vanethos. I will start working on it.

**Comment by Thesmader** [comment]
I'm done with the basic parts of the screen. I will need the image and content to complete the work.

**Comment by Vanethos** [comment]
@Thesmader
The text is in the first post.

As for the image, could you please put a placeholder?

Additionally, we are waiting for the contacts information, so please setup the layouts with mock data assuming that you are receiving data objects with the format given in the issue

**Comment by Thesmader** [comment]
Alright, I'll do that.

**Comment by Vanethos** [comment]
@Thesmader any news on the PR?

**Comment by Thesmader** [comment]
Sorry for the delay. I was busy with my classes. I am almost done with the work. Will open the PR soon.

**Comment by Thesmader** [comment]
This was my first Hacktoberfest. Thank you for letting me work on this repo. I learned to write good code by seeing the code in this repo. It was a lovely experience for me.

**Comment by Vanethos** [comment]
Thank you so much @Thesmader your comment surely made my week! :D 

Anytime you want to contribute to this or other projects, please do let me know! You can ping me at  https://twitter.com/GonPalma !
