### ISSUE TITLE
Occurrence Widget - Status

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#19]
**Description**
Separate widget for the Status of the Occurrences.

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- Widget that with the `Occurrences` object displays information about:
    - Status
    - Last update

**UI**

<img width="342" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63056074-318fc180-bedf-11e9-89cd-3800012fa0e1.png">

**NOTES**
Until the API Is completed, assume that this widget has as an input 1 `DateTime` objects and a `String`.

**Comment by OldMetalmind** [comment]
I'll be working on this widget together with @jmigueldcarvalho.

**Comment by Lima21** [comment]
I will do this issue

**Comment by Vanethos** [comment]
Closed via #92
