### ISSUE TITLE
Occurrences Widget - Start and End

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#22]
**Description**
 Separate widget for the "Start and End" of the Occurrences.

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- Widget that with the `Occurrences` object displays information about:
    - Start and end of the occurrence
    - Last updated

**UI**

<img width="599" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63056429-f04be180-bedf-11e9-94de-44cc8c17d83a.png">

**NOTES**
Until the API Is completed, assume that this widget has as an input 3 `DateTime` objects.

**Comment by TomerPacific** [comment]
@Vanethos , is this issue still up for grabs?

**Comment by OldMetalmind** [comment]
Hello @TomerPacific it still is. Thumbs up 👍 this message and I'll assign it to you.

**Comment by TomerPacific** [comment]
@OldMetalmind , is there anything specific I should be aware of? Do you want to separate it into two widgets? Naming conventions? Stateless/Stateful?

**Comment by Vanethos** [comment]
@TomerPacific 

This Widget shpuld be Stateless.

Since there are no other widgets yet for this project, I'd name it as `OccurrencesTimeWidget`, or anything that you feel might be proper for this widget.

This can be one widget only

Anything else, we'll be here to help you!

**Comment by TomerPacific** [comment]
@Vanethos , I have built a rough draft of the widget, but when trying to run the application, I get the following error:

> Compiler message:
../Flutter%20SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.7/lib/flare.dart:601:14: Error: The method 'FlutterActor.makeShapeNode' has fewer positional arguments than those of overridden method 'Actor.makeShapeNode'.
  ActorShape makeShapeNode() {
             ^
../Flutter%20SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flare_dart-1.4.8/lib/actor.dart:68:14: Context: This is the overridden method ('makeShapeNode').
  ActorShape makeShapeNode(ActorShape source) {
             ^
Compiler failed on C:\Users\Tomer\Documents\mobile-app\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Tomer\Documents\Flutter SDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\Users\Tomer\Documents\Flutter SDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

Obviously, I have not touched the Flare library and wanted to know if you have encountered this error. I did notice there is a newer version out [there](https://pub.dev/packages/flare_flutter/versions), but didn't want to upgrade without your consideration (might fix the issue).

**Comment by Vanethos** [comment]
@TomerPacific , a couple of questions:

- Are you on branch develop?
- Can you put here the output of `flutter doctor`?

Because on our end the app is running, in fact in each commit Travis tries to build the app, so supposedily it should be working in the latest `stable` branch of Flutter (I also tested building the app now and it worked)

**Comment by TomerPacific** [comment]
@Vanethos ,
I have branched out from develop into **feature/Occurrences-Widget-22**.

Running `flutter doctor` yields:

> $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.356], locale en-IL)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

I'm going to try returning to develop and running the application from there.

_UPDATE_
switched back to develop/imported the project again to Android Studio and got the same results

**Comment by Vanethos** [comment]
A quick question, if you update Flare's, can you run the app?

If so, and with no problem, please create a new PR just with that update, I'll approve it and you can then continue working on this.

Sorry for this experience btw! But on my end I'm not having any issues so it's hard to help and debug it :(

**Comment by TomerPacific** [comment]
@Vanethos ,
I have applied what you have suggested and the application runs now. 
I have upgraded the Flare package to the latest version, [1.5.15](https://pub.dev/packages/flare_flutter/versions), which was released yesterday.

Do you want me to open an issue and then a pull request to reference it?

The issue might originate from my flutter version?

`Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (12 days ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
`

**Comment by Vanethos** [comment]
@TomerPacific if you could open the issue and send the PR that would be awesome 🙏

**Comment by TomerPacific** [comment]
@Vanethos , an[ issue](https://github.com/vostpt/mobile-app/issues/69) has been opened and a [PR ](https://github.com/vostpt/mobile-app/pull/70)has been made.

**Comment by Vanethos** [comment]
@TomerPacific done!

**Comment by TomerPacific** [comment]
@Vanethos ,

this is what I have come up with :

![vostro](https://user-images.githubusercontent.com/23402988/66655312-82ecd080-ec44-11e9-97aa-3b76b6b4547a.jpg)

I have a few questions before opening a PR:

1. The text on the bottom row has been downscaled to fit the width of the container. Instead of entering a scale which may not fit all screens, do you allow the use of the [auto size text](https://github.com/leisim/auto_size_text) library?
2. The layout outline of the widget is as follows: 
                                                                

```
Material 
  |
Container
 |
Column
 |     |
Row   Row
 |
Column
```

Would you have preferred a different layout for this widget?
3. The widget takes three DateTime parameters for start, end and lastUpdated time
4. I have tested this page by routing the about page in the menu to open the widget.

**Comment by Vanethos** [comment]
@TomerPacific 
- You still need to put inside an element like a card, just as it is in the original post.
- As of the autosize library, it is best to open a different issue and a PR just for that.
- What happens if one of the date-time elements, end for example, is null?

Other than that, I have to say I was fairly impressed with such detailed and informative comment. This is great quality content for an open-source project. Great work 👏

**Comment by TomerPacific** [comment]
@Vanethos ,
thanks for the feedback.
In response to what you wrote:

-  There is no mention of a Card element (or at least I didn't understand there was a requirement for one), so I just want to make sure i understand. You would like the hierarchy to contain a card element that the dates will be displayed on?

- If you request a different issue and PR for the autosize library, do you prefer that I leave things as they are regarding the size of the text?

- Your third question is a great one, since I have already implemented code (when I posted my comment) to tackle this issue.  Meaning, that if the dateTime object is null, then all that will display is "--" (per the example).

If there is anything more that is required, please let me know.

**Comment by Vanethos** [comment]
@TomerPacific 

- When I say "card" it can be a container with a background! As you can see from the image, it has a rectangle all around it with some drop shadow

- Yes, leave things as they are!

- Yep that is what it is intended!

**Comment by TomerPacific** [comment]
@Vanethos ,
I have opened a [PR](https://github.com/vostpt/mobile-app/pull/71).

**Comment by Vanethos** [comment]
Hey @TomerPacific ! I've commented the PR and requested changes!

Great work so far!

**Comment by TomerPacific** [comment]
@Vanethos , I have reviewed all your comments and updated the PR.
