### ISSUE TITLE
Occurrences List

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#25]
**Description**
List of the VOST occurrences

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- Shows a list of occurences with the following data:
    - Occurence Type
    - Parish
    - Status
    - Last Updated
    - Is the user following the occurence? (symbolized by the start icon)

- This screen will either show the **most recent** occurrences or the **"following"** occurrences

- If the list is empty, an empty screen is shown

**UI**
Lis of Occurences:
<img width="412" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63056948-0d34e480-bee1-11e9-9d1d-1bc25ff0bfa1.png">

Empty Screen:
<img width="412" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63056986-22aa0e80-bee1-11e9-825c-13ee675845bb.png">

**Comment by Lima21** [comment]
I will do this issue :)
