### ISSUE TITLE
Load markers into the map

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#29]
**Description**
With the list of occurrences, show all the markers in the map so that the user can see them.

**File Location**
```
- presentation
|__ ui
```

**Requirements**
- When opening the map screen, we should show all the available markers at the same time plus the location of the user.
- The markers should have a callback so that when clicked they show a detail, as explained in #30

**UI**

<img width="415" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63057483-402ba800-bee2-11e9-8cf0-32fc0e17d08f.png">

**Comment by Lima21** [comment]
I will do this ;)
