### ISSUE TITLE
Clicking on a marker shows the Occurrence Details

### ISSUE THREAD

**Issue by Vanethos** [vostpt/mobile-app#30]
**Description**
Clicking on the marker on a map should show a small detail about the occurence. It is possible to expand this detail to ger more information.

**File Location**
```
- presentation
|__ ui
```

**Pre-Requisites**
- #19 
- #20 
- #21 
- #22 
- #29 
- #28

**Requirements**
- Clicking on the map marker should:
    - Center the pin on the screen
    - Highlight the marker
    - Show the Occurence Type Widget for that marker
    - Show a Floating Action that when clicked shows all the widgets for the occurences in a list
        - When clicked on the FAB again this list disappears
        - When clicking on the map screen, the list disappears

**UI**

<img width="417" alt="imagem" src="https://user-images.githubusercontent.com/10728633/63057720-cb0ca280-bee2-11e9-887e-fff4abf397fa.png">

Clicking on the FAB should expand with all the details that were created in #19, #20, #21 and #22

**Comment by Vanethos** [comment]
@OldMetalmind the screenshot for the expanded detail screen must be added

**Comment by OldMetalmind** [comment]
**UI Expanded**
<img width="395" alt="Screenshot 2019-08-16 at 13 58 44" src="https://user-images.githubusercontent.com/404874/63169178-0a93d580-c02e-11e9-9b5d-66f0a0bc47a9.png">

This screen reuses components from the Occurrence Detail Screen as mentioned as "required" in the description of the issue.

**Comment by CodeGlitch** [comment]
Hello! If no one is working on this issue, I would like to try to help, please assign this issue to me :)

**Comment by OldMetalmind** [comment]
@CodeGlitch done, thanks for helping, let us know if you have any question.

**Comment by CodeGlitch** [comment]
Do we have the files for the firefighter/firetruck/airplanes images above? Or should I use something else?

**Comment by CodeGlitch** [comment]
I've submitted a suggestion for this issue. The commit with the graddle might not be necessary, at least i couldnt compile and install on Android without updating it.
On https://github.com/vostpt/mobile-app/pulls seems to end with error, but I think that's because of the missing keys,dart?
Tell anything you need to help
