### ISSUE TITLE
Use different Primary and Secondary Colors

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/mobile-app#46]
As recommended by Francisco, we should avoid using the colors Green and Yellow, since they are used as an information, we should follow the color palette created for VOST

https://drive.google.com/file/d/1qLIXjp_nSWs8kpMdLFcNj9NQvxNyBsCb/view

We need to find proper Material colors that fit well with the VOST palette of Blue and that are inclusive.
Then update the project with the new colors.

**Comment by OldMetalmind** [comment]
@ffrutuoso can you try out this tool and find a nice couple of Primary an Secondary?
I tried out with the 'Informacao' (Blue) and Wisteria

https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=1E66DE&secondary.color=B9AFF0

Try out in the Figma, feel out the colors.

**Comment by ffrutuoso** [comment]
New color palette here: [https://material.io/resources/color/...]( https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=1E66DE&secondary.color=E0E0E0&primary.text.color=ffffff)

Still needs to be tested further, but this is the starting point.


![Screen Shot 2019-08-20 at 18 52 55](https://user-images.githubusercontent.com/13594537/63371328-ca10c080-c37b-11e9-9aea-02805a3484f6.png)

**Comment by diegoalvis** [comment]
@OldMetalmind 
I'd like to contribute to this issue. I already have some work in progress with an app theme component using the new color palette.

**Comment by OldMetalmind** [comment]
assigned to you @diegoalvis
